{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "fbx.secretName" . }}
  labels:
    {{- include "fbx.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ include "fbx.secretName" . }}
    creationPolicy: Owner
  data:
    {{- $remote := .Values.externalSecret.remoteSecretName }}
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ required "externalSecret.remoteSecretName is required" $remote }}
        property: {{ .property }}
    {{- end }}
    {{- range .Values.externalSecret.extraData }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteSecretName }}
        property: {{ .property }}
    {{- end }}
{{- end }}
