apiVersion: v1
kind: Service
metadata:
  name: {{ include "fbx.name" . }}
  labels:
    {{- include "fbx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "fbx.selectorLabels" . | nindent 4 }}
  ports:
    # Port names carry the protocol prefix Istio uses for protocol selection.
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      appProtocol: http
    - name: http-management
      port: {{ .Values.service.managementPort }}
      targetPort: management
      appProtocol: http
