
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: loan-lifecycle-service-secrets
  labels:
    app.kubernetes.io/name: loan-lifecycle-service
    app.kubernetes.io/instance: ci
    app.kubernetes.io/component: service
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/part-of: fintechbankx-lending
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: fintechbankx-service-0.1.0
    fintechbankx.io/service-id: svc-ln-loan-lifecycle
    fintechbankx.io/context: lending
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: "ClusterSecretStore"
    name: "aws-secrets-manager"
  target:
    name: loan-lifecycle-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: "SPRING_DATASOURCE_PASSWORD"
      remoteRef:
        key: "staging/loan-lifecycle-service/db-app"
        property: "password"
    - secretKey: "OIDC_CLIENT_SECRET"
      remoteRef:
        key: "staging/loan-lifecycle-service/oidc-client"
        property: "client_secret"
