#!/usr/bin/env bash
# Database per service for the local/ephemeral runtime. For every row of
# services.tsv: a LOGIN role (credential from the env var named in the row,
# generated by compose/scripts/init-env.sh), a database owned by that role
# that no other role may connect to, and the service schema owned by the role
# (Flyway in the service creates its tables there). Re-runnable.
#
# Runs as a docker-entrypoint-initdb.d script in the postgres container, or
# against any server via the usual PG* variables.
set -euo pipefail

services="${FBX_SERVICES_TSV:-/fbx/services.tsv}"
superuser="${PGUSER:-${POSTGRES_USER:-postgres}}"
psql_admin() { psql -X -q -v ON_ERROR_STOP=1 --username "$superuser" "$@"; }

while IFS=$'\t' read -r key service_id _ database schema role cred_var _ _; do
  [[ -z "$key" || "$key" == \#* ]] && continue
  cred="${!cred_var:-}"
  [ -n "$cred" ] || { echo "[db-init] $cred_var is not set for $key" >&2; exit 1; }
  echo "[db-init] $service_id: database $database, schema $schema, role $role"

  psql_admin --dbname postgres -v role="$role" -v cred="$cred" -v db="$database" <<'SQL'
SELECT format('CREATE ROLE %I LOGIN', :'role')
 WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'role') \gexec
SELECT format('ALTER ROLE %I WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD %L', :'role', :'cred') \gexec
SELECT format('CREATE DATABASE %I OWNER %I', :'db', :'role')
 WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'db') \gexec
SELECT format('REVOKE ALL ON DATABASE %I FROM PUBLIC', :'db') \gexec
SELECT format('GRANT CONNECT, TEMPORARY ON DATABASE %I TO %I', :'db', :'role') \gexec
SQL

  if [ "$schema" != "public" ]; then
    psql_admin --dbname "$database" -v role="$role" -v schema="$schema" <<'SQL'
SELECT format('CREATE SCHEMA IF NOT EXISTS %I AUTHORIZATION %I', :'schema', :'role') \gexec
SELECT format('ALTER SCHEMA %I OWNER TO %I', :'schema', :'role') \gexec
SELECT format('ALTER ROLE %I IN DATABASE %I SET search_path = %I', :'role', current_database(), :'schema') \gexec
SQL
  fi
done < "$services"
echo "[db-init] done"
