# dev overrides.
environment: dev
externalSecret:
  remoteSecretName: dev/example-service/db-app
replicaCount: 2
autoscaling:
  minReplicas: 2
  maxReplicas: 4
podDisruptionBudget:
  minAvailable: 1
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 768Mi
